#!/usr/bin/env python3
"""Generate Markdown comparison tables from the canonical TOYOPUC JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "capability" / "toyopuc_profiles.json"
TABLE_DIR = ROOT / "tables"
OPTION_DEFINITIONS = [
    (
        "use_upper_u_pc10",
        "Upper U via PC10",
        "Allows the upper U range through PC10 addressing when the selected profile exposes that range.",
    ),
    (
        "use_eb_pc10",
        "EB via PC10",
        "Uses the PC10 extended addressing path for the EB area where the profile exposes EB.",
    ),
    (
        "use_fr_pc10",
        "FR via PC10",
        "Uses the PC10 FR block and commit-capable path for the FR area where the profile exposes FR.",
    ),
    (
        "use_upper_bit_pc10",
        "Upper prefixed bits via PC10",
        "Allows upper prefixed bit ranges such as the 1000-series P/V/T/C/L ranges through PC10-derived addressing.",
    ),
    (
        "use_upper_m_bit_pc10",
        "Upper M bits via PC10",
        "Allows the upper M bit range through PC10-derived addressing.",
    ),
]


def load_catalog() -> dict[str, Any]:
    return json.loads(CATALOG.read_text(encoding="utf-8"))


def cell(value: object) -> str:
    text = "-" if value is None else str(value)
    if text == "":
        text = "-"
    text = text.replace("|", "\\|")
    return text


def markdown_table(headers: list[str], rows: list[list[object]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(value) for value in row) + " |")
    return "\n".join(lines)


def yes_no(value: bool) -> str:
    return "yes" if value else "no"


def format_range(range_value: dict[str, int], width: int) -> str:
    return f"{range_value['start']:0{width}X}..{range_value['end']:0{width}X}"


def format_ranges(ranges: list[dict[str, int]], width: int) -> str:
    return ", ".join(format_range(range_value, width) for range_value in ranges) if ranges else "-"


def profile_table(payload: dict[str, Any]) -> str:
    rows: list[list[object]] = []
    for profile_id, profile in payload["profiles"].items():
        options = profile["addressing_options"]
        rows.append(
            [
                profile_id,
                profile["display_name"],
                len(profile["areas"]),
                *[yes_no(options[key]) for key, _, _ in OPTION_DEFINITIONS],
                "Unconfirmed",
            ]
        )
    option_rows = [[label, key, meaning] for key, label, meaning in OPTION_DEFINITIONS]
    return "\n\n".join(
        [
            "# TOYOPUC Computer Link Profile Parameters",
            "<!-- Generated by tools/generate_profile_tables.py. Do not edit manually. -->",
            "Generated user-facing reference. Source: capability/toyopuc_profiles.json.",
            f"Schema {payload.get('schema_version', '-')}, date {payload.get('date', '-')}, scope {payload.get('scope', '-')}.",
            "## Purpose",
            "Profile parameters document canonical TOYOPUC Computer Link profile IDs, display names, area counts, and addressing option behavior for user manuals and profile-selection tools.",
            "They do not prove that every address will be accepted by a connected PLC; the actual model, route, project settings, and write permissions can still reject a request.",
            "## Profile Summary",
            markdown_table(
                [
                    "Profile ID",
                    "Display name",
                    "Area count",
                    *[label for _, label, _ in OPTION_DEFINITIONS],
                    "Verified models",
                ],
                rows,
            ),
            "## Addressing Option Definitions",
            markdown_table(["Option", "JSON field", "Meaning"], option_rows),
            "## Appendix: How To Read Cells",
            "- means no value applies to that profile.",
            "yes and no indicate whether the profile enables that addressing option by default.",
            "Unconfirmed means this catalog entry is adopted from existing profile data without a live-device verification record for that exact profile in this repository.",
            "",
        ]
    )


def ordered_areas(payload: dict[str, Any]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for profile in payload["profiles"].values():
        for area in profile["areas"]:
            name = area["area"]
            if name not in seen:
                seen.add(name)
                result.append(name)
    return result


def area_map(profile: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {area["area"]: area for area in profile["areas"]}


def area_cell(area: dict[str, Any] | None, attribute: str) -> str:
    if area is None:
        return "-"
    width = area["address_width"]
    if attribute == "direct_ranges":
        return format_ranges(area["direct_ranges"], width)
    if attribute == "prefixed_ranges":
        return format_ranges(area["prefixed_ranges"], width)
    if attribute == "supports_packed_word":
        return yes_no(area["supports_packed_word"])
    if attribute == "address_width":
        return str(width)
    if attribute == "suggested_start_step":
        return f"0x{area['suggested_start_step']:X}"
    if attribute == "packed_direct_ranges_override":
        return format_ranges(area.get("packed_direct_ranges_override", []), max(1, width - 1))
    if attribute == "packed_prefixed_ranges_override":
        return format_ranges(area.get("packed_prefixed_ranges_override", []), max(1, width - 1))
    raise KeyError(attribute)


def area_matrix(payload: dict[str, Any], title: str, attribute: str) -> str:
    profiles = payload["profiles"]
    profile_ids = list(profiles)
    maps = {profile_id: area_map(profile) for profile_id, profile in profiles.items()}
    rows = [
        [area] + [area_cell(maps[profile_id].get(area), attribute) for profile_id in profile_ids]
        for area in ordered_areas(payload)
    ]
    return "\n\n".join([f"## {title}", markdown_table(["Area"] + profile_ids, rows)])


def area_table(payload: dict[str, Any]) -> str:
    attribute_rows = [
        ["Direct ranges", "Direct area address ranges for unprefixed access."],
        ["Prefixed ranges", "Program-prefixed ranges such as P1-D0000 when the area supports that form."],
        ["Packed word", "Whether bit-style points can be packed into word-oriented PC10 access for that profile and area."],
        ["Width", "Hex digit width used when rendering addresses for the area."],
        ["Step", "Suggested hexadecimal start-step for UI pickers and scan planning."],
        ["Packed direct override", "Optional packed-word range override for direct access."],
        ["Packed prefixed override", "Optional packed-word range override for prefixed access."],
    ]
    return "\n\n".join(
        [
            "# TOYOPUC Computer Link Area Ranges",
            "<!-- Generated by tools/generate_profile_tables.py. Do not edit manually. -->",
            "Generated user-facing reference. Source: capability/toyopuc_profiles.json.",
            f"Schema {payload.get('schema_version', '-')}, date {payload.get('date', '-')}, scope {payload.get('scope', '-')}.",
            "## Purpose",
            "Area ranges compare TOYOPUC Computer Link direct, prefixed, packed, width, and step attributes across canonical profiles.",
            "They are catalog data for profile selection, UI address pickers, diagnostics, and application-layer validation, not a production guarantee that every address can be read or written on a connected PLC.",
            "## Area Attribute Definitions",
            markdown_table(["Attribute", "Meaning"], attribute_rows),
            area_matrix(payload, "Direct Range Matrix", "direct_ranges"),
            area_matrix(payload, "Prefixed Range Matrix", "prefixed_ranges"),
            area_matrix(payload, "Packed Word Matrix", "supports_packed_word"),
            area_matrix(payload, "Address Width Matrix", "address_width"),
            area_matrix(payload, "Suggested Step Matrix", "suggested_start_step"),
            area_matrix(payload, "Packed Direct Override Matrix", "packed_direct_ranges_override"),
            area_matrix(payload, "Packed Prefixed Override Matrix", "packed_prefixed_ranges_override"),
            "## Appendix: How To Read Cells",
            "- means the area or attribute is not available for that profile.",
            "Range cells use inclusive hexadecimal start..end notation.",
            "yes and no in the packed-word matrix indicate whether packed-word access is available for the area in that profile.",
            "Width is the number of hexadecimal address digits. Step is the suggested hexadecimal increment for UI pickers or scan planning.",
            "",
        ]
    )


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            print(f"stale generated table: {path.relative_to(ROOT)}")
            return False
        print(f"fresh generated table: {path.relative_to(ROOT)}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated tables are stale")
    args = parser.parse_args()

    payload = load_catalog()
    outputs = {
        TABLE_DIR / "toyopuc_profile_parameters.md": profile_table(payload),
        TABLE_DIR / "toyopuc_area_ranges.md": area_table(payload),
    }
    ok = all(write_or_check(path, content, args.check) for path, content in outputs.items())
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
